### ISSUE TITLE
Old SdFat Version.

### ISSUE THREAD

**Issue by RattyDAVE** [MockbaTheBorg/CPMduino#6]
In the read me you are using https://github.com/greiman/SdFat . The included one is an old version. 

Can you update your code so it uses the current version? 

There is a lot of changes mostly speed improvements and more compatibility.

Below are errors with the current version. 

Looking at it it looks like getFilename needs to be sorted in a few places. (I dont know your code so unaware of the impact.)

Thank you!

```
In file included from /home/dave/Dropbox/Projects/git/Code/Arduio Stuff/CPMduino/CPMduino.ino:14:0:
sketch/abstraction_arduino.h: In function 'bool findFirst(uint8*, uint8*)':
abstraction_arduino.h:189: error: 'class SdFile' has no member named 'getFilename'
   dir.getFilename((char*)dirname);
       ^
sketch/abstraction_arduino.h: In function 'bool findNext(uint8*, uint8*)':
abstraction_arduino.h:213: error: 'class SdFile' has no member named 'getFilename'
   dir.getFilename((char*)dirname);
       ^
abstraction_arduino.h:223: error: 'class SdFile' has no member named 'getFilename'
   dir.getFilename((char*)dirname);
       ^
exit status 1
'class SdFile' has no member named 'getFilename'
```

**Comment by MockbaTheBorg** [comment]
Done ... please give it a try ... I believe it is working fine, but it is always good to have a second set of eyes.
Be aware that you need USE_LONG_FILE_NAMES set to 0.

Cheers!

**Comment by RattyDAVE** [comment]
WOW. You are a Borg! I didn't expect a response so quick!

Ill try in a bit.

**Comment by RattyDAVE** [comment]
Just tried and what a result. Perfect!
