### ISSUE TITLE
SdFat library outdated

### ISSUE THREAD

**Issue by kklis** [MockbaTheBorg/CPMduino#7]
After commit https://github.com/MockbaTheBorg/CPMduino/commit/9e21d6ada6f0f451228d7cd516640451f4a4f0cb
CPMduino doesn't not compile with SdFat version provided in https://github.com/MockbaTheBorg/CPMduino/tree/master/SdFat displaying error status:
`'class SdFile' has no member named 'getName'`
Please consider updating it to the latest version, as it compiles with the latest master from https://github.com/greiman/SdFat
Thanks!

**Comment by kklis** [comment]
Maybe when updating the library you could also add:
`define USE_LONG_FILE_NAMES 0`
to SdFatConfig.h as well?

**Comment by kklis** [comment]
I prepared a pull request with changes I suggested above: https://github.com/MockbaTheBorg/CPMduino/pull/8

**Comment by MockbaTheBorg** [comment]
I was in the process of changing it already. I believe it is going to be ok now.
Please run a sanity check just to be sure.

**Comment by kklis** [comment]
Just checked against all test scenarios we tested with latest fixes, and it works fine.
